### ISSUE TITLE
can this be combined with darq?

### ISSUE THREAD

**Issue by feiwaltan** [felixblaschke/supercharged#3]
https://github.com/andrewackerman/darq

Seems to offer a lot of the same capabilities, and is focused purely only iterables and yours seems to do both iterables and date time. Would be nice just reference one package instead of two different one.

**Comment by felixblaschke** [comment]
Supercharged extends more then just iterables and dates. Have a look at the api documentation: https://pub.dev/documentation/supercharged/latest/supercharged/supercharged-library.html

Since you can control the usage of packages via imports there is no problem in using two different packages.

I don't see a merge of packages at this point. Packages may differ in effort, influence, size and style. This variety is always good for the user. Just pick what is best for you.
