### ISSUE TITLE
Suggest change behavior of String.toInt and String.toDouble

### ISSUE THREAD

**Issue by cdhigh** [felixblaschke/supercharged#7]
toInt/toDouble should return 0/0.0 if exception, at lease has a option for it.
current implements are same of 'int.tryParse/double.tryParse'.
after that, the user has to check the result is null or not.

**Comment by felixblaschke** [comment]
Thank you for your feedback. I thought about this and want to share my opinion with you. 

Basically there can be 3 strategies on how to handle an error if something goes wrong. Throwing an expection, returning null or providing a default value.

Since exception throwing produce a lot of code overhead I prefer the other options. As you correctly pointed out, the current implementation returns null. I understood that you'd like to have an easier way to handle parse errors, by avoiding null.

I don't think we need to change it because since dart 2.3 the language has strong mechanisms to handle nullability. We can handle your case by using the "if null operator" (`??`)

```dart
var value = "invalid".toInt() ?? 0.0;
```

If we implement a default value mechanism, it would look like this:

```dart
var value = "invalid".toInt(defaultValue: 0.0);
```

The first option produces less code and is equal to the second option from a readibility point of view. Also each dart developer should be familiar with the `??` operator. It's the language mechanism to handle nullability.

It feels unnatural for me to work around the language.

**Comment by cdhigh** [comment]
You mentioned 3 strategies, and Dart has bulitin support for ALL of them:    
Throwing an expection: `int.parse()`.   
Returning null: `int.tryParse()`.    
Providing a default value: `int.tryParse() ?? 0`.   

Currently I use this form without any package:     
`var value = Int.tryParse('invalid') ?? 0;`.   
But It has many ?? In large function fromJSON.    
Your package should be more convenient than the built-in function Instead of repeating.

**Comment by felixblaschke** [comment]
I don't see any improvement offering a `defaultValue` parameter over the language wide `??`. You shouldn't consider a `??` as something bad. Every dart developer will know, you are provoding a default value by using `??`.

Once you learned it, you can produce very readable code. It's a feature on **language level**. Using `defaultValue` is only on **API level**. Other package might name it `onErrorValue` or `defaultValue` or `elseValue`. It isn't consistent. But using `??` is a concept that can be applied language-wide.

Also `toInt` should be a shortage for `int.parse`. It's shouldn't do anything more. It has just to goal to offer a fluent api. This allows the following code readability:

```dart
var value = someService.getData().someField.toInt() ?? 0;
```
I access a service, fetch some data, access the field and covert it's value to int. From left to right in logical order.
